spring.application.name=Auctionsystem
# Kết nối MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/auction_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Ducanh231206@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Cấu hình Hibernate
# CHỈ DÙNG 'create' TRONG LẦN CHẠY ĐẦU TIÊN ĐỂ TẠO BẢNG
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# Hiện chi tiết lỗi khởi tạo Bean và JPA
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.tool.schema=DEBUG

# Hiện lỗi khi thực hiện truy vấn

logging.level.org.hibernate.SQL=DEBUG
